### ISSUE TITLE
Have you considered adopting the metropolis theme?

### ISSUE THREAD

**Issue by samcarter** [jolars/moloch#3]
Just curious: have you considered adopting the metropolis theme instead of publishing this as a new theme? While I will happily direct all users, who face problems with metropolis, to your theme, there will still be many users out there who will keep using metropolis. This means that beamer can't remove all the patches of patches of patches which currently prevent metropolis from breaking completely.

If metropolis were to use the LPPL license, there would be a build in route for a possible adoption, I don't know how the metropolis license influences the process, but if your are interested, maybe you could ask CTAN for advise https://ctan.org/help/become-author

**Comment by jolars** [comment]
I did consider something along this route, but since I also wanted to get rid of some features in Metropolis and didn't want to break anything for existing users, this felt like the safer route. 

That being said, it might still be a good idea for someone (not necessarily me) to take over the metropolis theme and take care of some of the bugs.

**Comment by samcarter** [comment]
Thanks for your reply! A new theme makes it indeed easier to remove options etc.
